
title: Perfil profesional de Carlos Freire Acebedo
url: 'carlos-freire-acebedo.github.io'
baseurl: '' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Carlos Freire Acebedo
tagline: Analista programador .NET
pic: carlos-freire-acebedo.jpeg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
linkedin: carlos-freire-acebedo
github: carlos-freire-acebedo

#Update all the sections by editing the files inside _includes folder.
